name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ESLint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend ESLint
        working-directory: ./frontend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend ESLint
        working-directory: ./backend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend Prettier
        working-directory: ./frontend
        run: npx prettier --check .

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend Prettier
        working-directory: ./backend
        run: npx prettier --check .
